### PR TITLE
Fixed Image Links

### LINKED ISSUE #1: Images are not showing.
Screenshot_20211118_005401
The images are not showing up. I've tried refresing, but it's not working.

### PR DESCRIPTION
**Pull request by rakshit087**
This will fix #1 
Changed the links to relative links.

### CODE REVIEW

**Comment by altsam** [comment]
Hey @rakshit087 
The images load fine in [LEARN.md](https://github.com/altsam/create_crypto_with_solana_cli/blob/main/LEARN.md).
Need to discuss the cause of issue with Questbook folks, probably an issue with the renderer.
Also, relative paths won't work as per [the guide to writing quests](https://questbook.notion.site/How-to-create-a-quest-for-Questbook-e839311948184de799a71445028db3eb).

**Comment by rakshit087** [comment]
Ahh, right got it. 
I thought relative paths will fix it, but since the md file is being used somewhere else, it won't work.

**Comment by rakshit087** [comment]
Will close the PR for now xD

**Comment by rakshit087** [comment]
So I figured, we can use the raw content links. 
I will make a small commit and see if it works.

**Comment by rakshit087** [comment]
This should work, since it is also working in my offline view  

Previously  

Screenshot_20211120_234444

Now  

Screenshot_20211120_234527

**Review by altsam — APPROVED** [review]

**Comment by altsam** [comment]
Thanks a lot @rakshit087 !
Seems to be working now :smile:

**Comment by rakshit087** [comment]
Thank You for merging :)

**Pull request merged**
